### PR TITLE
Add column count to tables comment (#6)

### PR DESCRIPTION
**Pull request by owenconti**
Original PR: https://github.com/ohseesoftware/laravel-schema-list/pull/6

### CODE REVIEW

**Comment by owenconti** [comment]
Thanks for your help @innoflash!

**Comment by innoflash** [comment]
@owenconti u got it. 

Do you think we need row count as well?

**Comment by owenconti** [comment]
@innoflash probably wouldn't hurt as long as performance is okay with giant tables

**Comment by innoflash** [comment]
Copy that, let me cook the PR soon

**Pull request merged**
